#Using a list to implement matrix (MAnualy and without numpy)

In [10]:
r = 2 #int(input("Enter number of rows:"))
c = 2 #int(input("Enter number of columns:"))

matrix=[]

for i in range(r):
    row=[]
    for j in range(c):
       row.append(int(input("Enter element of [{}][{}]:".format(i,j))))
       matrix.append(row)
print(matrix)

# for i in range (r):
#    for j in range(c):
#        print(matrix[i][j], end=" ")
#    print("")

[[1, 2], [1, 2], [3, 4], [3, 4]]


#numpy

In [14]:
import numpy as np

r = int(input("Enter number of rows:"))
c = int(input("Enter number of columns:"))

print("Enter data in single line separated by spaces")

data = list(map(int, input().split()))

matrix = np.array(data).reshape(r,c)

print(matrix)

Enter data in single line separated by spaces


ValueError: cannot reshape array of size 0 into shape (3,3)

#Using list, create two matrices, perform addition and subtract operation.

In [26]:
import numpy as np

m1 = [[1,2],[3,4],[6,7]]
m2 = [[5,6],[7,8],[9,1]]

m1 = np.array(m1).reshape(3,2)
m2 = np.array(m2).reshape(3,2)

print('First Matrix:')
print(m1)
print('Second Matrix:')
print(m2)

add= np.add(m1,m2)
print('Addition:')
print(add)

sub= np.subtract(m1,m2)
print('Subtraction:')
print(sub)


First Matrix:
[[1 2]
 [3 4]
 [6 7]]
Second Matrix:
[[5 6]
 [7 8]
 [9 1]]
Addition:
[[ 6  8]
 [10 12]
 [15  8]]
Subtraction:
[[-4 -4]
 [-4 -4]
 [-3  6]]


#Multiplication and Division

In [34]:
import numpy as np

m1 = [[1,2,3],[3,4,6],[6,7,1]]
m2 = [[5,6,9],[7,8,1],[3,4,6]]

m1 = np.array(m1).reshape(3,3)
m2 = np.array(m2).reshape(3,3)

print(m1)
print(m2)

mul = m1.dot(m2)
print('Multiplication:')
print(mul)

div= np.divide(m1,m2)
print('Division:')
print(div)

[[1 2 3]
 [3 4 6]
 [6 7 1]]
[[5 6 9]
 [7 8 1]
 [3 4 6]]
Multiplication:
[[28 34 29]
 [61 74 67]
 [82 96 67]]
Division:
[[0.2        0.33333333 0.33333333]
 [0.42857143 0.5        6.        ]
 [2.         1.75       0.16666667]]
